### ISSUE TITLE
function named 'bn_sqr_comba4' - how to trace further in sample-bt?

### ISSUE THREAD

**Issue by rkearsley** [openresty/nginx-systemtap-toolkit#34]
Hello

My output from sample-bt indicates that this function 'bn_sqr_comba4' is using by far/overwhelmingly more cpu time than anything else in an nginx worker, but I'm unable to trace it further as it's at the root level just above 'all' in the flamegraph

a small piece:

>  0x7f15cb4a41e3 : bn_sqr_comba4+0x26f3/0x88d0 [/lib/x86_64-linux-gnu/libcrypto.so.1.0.0]
>          104
>   0x7f15cb4a4213 : bn_sqr_comba4+0x2723/0x88d0 [/lib/x86_64-linux-gnu/libcrypto.so.1.0.0]
>          103
>   0x7f15cb4a3d07 : bn_sqr_comba4+0x2217/0x88d0 [/lib/x86_64-linux-gnu/libcrypto.so.1.0.0]
>          97
>   0x7f15cb4a41f7 : bn_sqr_comba4+0x2707/0x88d0 [/lib/x86_64-linux-gnu/libcrypto.so.1.0.0]
>          93

How can I look further and find out which part of nginx is using this function?

Many thanks
Richard

**Comment by agentzh** [comment]
@rkearsley I think you should install the debuginfo package of your system's openssl library.

**Comment by rkearsley** [comment]
Thanks.
It was an inefficient ssl cypher having priority over others. Changed to some recommended ones and much better!
